@port=8000
@branch={{hostname}}:{{port}}/api/v1/account
@contentType=application/json
# @authToken=

###
GET http://{{branch}}/all

###
POST http://{{branch}}/signup
Content-Type: {{contentType}}

{
    "email": "hig@emovaw.za",
    "first_name": "Hilda",
    "last_name": "Ramirez",
    "phone": "41276641",
    "password": "4d3ig1bf8WWE6C"
}

###
POST http://{{branch}}/signin
Content-Type: {{contentType}}

{
    "email": "hig@emovaw.za",
    "password": "4d3ig1bf8WWE6C"
}
