@hostname_remote=https://pip-3103.herokuapp.com:443
@branch={{hostname_remote}}/api/v1/account
@contentType=application/json

###
GET {{branch}}/all

###
POST {{branch}}/signup
Content-Type: {{contentType}}

{
    "email": "hig@emovaw.za",
    "first_name": "Hilda",
    "last_name": "Ramirez",
    "phone": "41276641",
    "password": "4d3ig1bf8WWE6C"
}
### Exception handler
POST {{branch}}/signup
Content-Type: {{contentType}}

{"first_name": "561251", "last_name": "512515", "email": "nguyenchinhkhoi@gmail.com", "phone": "41276641", "password": "ytF4d6R65YqRUdb"}

###
POST {{branch}}/signin
Content-Type: {{contentType}}

{
    "email": "hig@emovaw.za",
    "password": "4d3ig1bf8WWE6C"
}

###
GET {{branch}}/me
Content-Type: {{contentType}}

{
    "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0eXAiOiJhY2Nlc3MiLCJleHAiOjE2MzkwNzU4NTksImlhdCI6MTYzOTA3MjI1OSwianRpIjoiZTRmMzc4ZWIxZDYxNGZkZWEzOTBmZjRjOWIwOTg3MTUiLCJ1dWlkIjoiZTJlNDU2OTEtYjZmYy00OTU2LTgwODAtZTgwOGQwZjVhZWVkIiwiaXNzIjoiUElQX1BJUCJ9.nIk_idfi5r0RTD9gogpw00QyMlACdf_9vP_MzuJWYOQ"
}

###
DELETE {{branch}}/signout
