@hostname_remote=https://pip-3103.herokuapp.com:443
@branch={{hostname_remote}}/api/v1/product
@contentType=application/json

###
GET {{branch}}/filter_list

###
GET {{branch}}/all

###
GET {{branch}}/popular

###
GET {{branch}}/detail?uuid=6d9349b0-7877-5f44-a863-888e273c3ab0

###
GET {{branch}}/search?key=iphone+12

###
GET {{branch}}/filter?toPrice=10000000
