@port=8000
@branch={{hostname}}:{{port}}/api/v1/product
@contentType=application/json
# @authToken=

###
GET http://{{branch}}/filter_list

###
GET http://{{branch}}/all

###
GET http://{{branch}}/popular

###
GET http://{{branch}}/detail?uuid=6d9349b0-7877-5f44-a863-888e273c3ab0

###
GET http://{{branch}}/search?key=iphone+12

###
GET http://{{branch}}/filter?toPrice=10000000
