@hostname_remote=https://pip-3103.herokuapp.com:443
@branch={{hostname_remote}}/api/v1/brand
@contentType=application/json

###
GET {{branch}}/all

###
GET {{branch}}/brand
Content-Type: {{contentType}}

{
    "uuid": "84093bb8-8496-596a-819b-2c443009a9d0"
}
